---
# Pihole
pihole_enable: true
pihole_hostname: pihole
pihole_timezone: America/Chicago
pihole_password: "admin"

# Prometheus
prometheus_enable: true

# Prometheus Speedtest Exporter
speedtest_enable: true
speedtest_interval: 60m

# Prometheus Ping Exporter
ping_enable: true
ping_interval: 5s
ping_hosts:  # [URL];[HUMAN_READABLE_NAME]
  - http://www.google.com/;google.com
  - https://github.com/;github.com
  - https://www.apple.com/;apple.com

# Grafana
grafana_enable: true
grafana_admin_password: "admin"
